import {
  Apple,
  Baby,
  Bike,
  BookOpen,
  Cake,
  Camera,
  Car,
  Coffee,
  Dumbbell,
  Flower,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Headphones,
  HeartPulse,
  Home,
  Lamp,
  Landmark,
  Laptop,
  Music,
  Package,
  Palette,
  PawPrint,
  Plane,
  Puzzle,
  Rocket,
  Shirt,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Speaker,
  Tent,
  TreePine,
  Trophy,
  Tv,
  Utensils,
  Watch,
  WashingMachine,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: { key: string; Icon: LucideIcon }[] = [
  { key: "headphones", Icon: Headphones },
  { key: "shirt", Icon: Shirt },
  { key: "lamp", Icon: Lamp },
  { key: "sparkles", Icon: Sparkles },
  { key: "footprints", Icon: Footprints },
  { key: "book-open", Icon: BookOpen },
  { key: "package", Icon: Package },
  { key: "watch", Icon: Watch },
  { key: "camera", Icon: Camera },
  { key: "gamepad", Icon: Gamepad2 },
  { key: "dumbbell", Icon: Dumbbell },
  { key: "coffee", Icon: Coffee },
  { key: "gift", Icon: Gift },
  { key: "home", Icon: Home },
  { key: "laptop", Icon: Laptop },
  { key: "smartphone", Icon: Smartphone },
  { key: "car", Icon: Car },
  { key: "baby", Icon: Baby },
  { key: "utensils", Icon: Utensils },
  { key: "palette", Icon: Palette },
  { key: "apple", Icon: Apple },
  { key: "bike", Icon: Bike },
  { key: "cake", Icon: Cake },
  { key: "flower", Icon: Flower },
  { key: "gem", Icon: Gem },
  { key: "heart-pulse", Icon: HeartPulse },
  { key: "landmark", Icon: Landmark },
  { key: "music", Icon: Music },
  { key: "paw", Icon: PawPrint },
  { key: "plane", Icon: Plane },
  { key: "puzzle", Icon: Puzzle },
  { key: "rocket", Icon: Rocket },
  { key: "shopping-cart", Icon: ShoppingCart },
  { key: "sofa", Icon: Sofa },
  { key: "speaker", Icon: Speaker },
  { key: "tent", Icon: Tent },
  { key: "tree", Icon: TreePine },
  { key: "trophy", Icon: Trophy },
  { key: "tv", Icon: Tv },
  { key: "washing-machine", Icon: WashingMachine },
  { key: "zap", Icon: Zap },
];

const iconByKey = new Map(CATEGORY_ICONS.map(({ key, Icon }) => [key, Icon]));

export function resolveCategoryIcon(key?: string | null, fallbackIndex = 0): LucideIcon {
  if (key) {
    const found = iconByKey.get(key);
    if (found) return found;
  }
  return CATEGORY_ICONS[Math.abs(fallbackIndex) % CATEGORY_ICONS.length].Icon;
}
